version: '3.8'

services:
  discord-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # Use BuildKit for cache mounts and multi-stage builds
      cache_from:
        - python:3.11-slim
      args:
        BUILDKIT_INLINE_CACHE: 1
      # Multi-platform support (optional)
      # platforms:
      #   - linux/amd64
      #   - linux/arm64
    image: discord-bot-framework:latest
    container_name: discord-bot-framework
    restart: unless-stopped
    
    # Environment variables
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    
    # Network configuration
    networks:
      - bot-network
    
    # Health check override
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; import os; sys.exit(0 if os.path.exists(\"worker_functions\") else 1)'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Networks
networks:
  bot-network:
    driver: bridge
    # Network security
    driver_opts:
      com.docker.network.bridge.name: bot-br0
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true" 